version: '3'
networks:
  react-frontend:
    external: true

services:
  react-frontend:
    container_name: react-frontend
    build:
      context: . # Making a docker image called react-frontend based on Dockerfile
    volumes:
      - ./:/app
    networks:
      - react-frontend
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
